// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vidoGameapi.Data;

#nullable disable

namespace vidoGameapi.Migrations
{
    [DbContext(typeof(VideoGameDbContext))]
    partial class VideoGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vidoGameapi.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Developer = "insomniac games",
                            Platform = "ps5",
                            Publisher = "sony interactive entertainment",
                            Title = "spider-man 2"
                        },
                        new
                        {
                            Id = 2,
                            Developer = "naughty dog",
                            Platform = "ps5",
                            Publisher = "sony interactive entertainment",
                            Title = "the last of us part 1"
                        },
                        new
                        {
                            Id = 3,
                            Developer = "nintendo",
                            Platform = "nintendo switch",
                            Publisher = "nintendo",
                            Title = "the legend of zelda: breath of the wild"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
